[package]
name = "oblivc-sys"
version = "0.1.0"
authors = ["Phillipp Schoppmann <schoppmann@informatik.hu-berlin.de>"]

[dependencies]
gcrypt = "0.5.4"

[build-dependencies]
walkdir = "2"
bindgen = "0.26.3"
