[package]
name = "test-oblivc"
version = "0.1.0"
authors = ["Phillipp Schoppmann <schoppmann@informatik.hu-berlin.de>"]

[dependencies]
oblivc = { path = "..", version = "0.1.0" }

[build-dependencies]
oblivc = { path = "..", version = "0.1.0" }
